Feat/product page
dartist21/fake-burrberry-frontend pull request #1
Opened 2017-08-01 04:19 UTC by dartist21

2017-08-01 11:53 UTC, evgenyrodionov commented
https://rawgit.com/dartist21/fake-burrberry-frontend/feat/product-page/index.html

![image](https://user-images.githubusercontent.com/775692/28824012-e08f15a2-76c8-11e7-8254-8c218213a221.png)
![image](https://user-images.githubusercontent.com/775692/28824034-f98d790e-76c8-11e7-8f4b-a4e612521ea4.png)
![image](https://user-images.githubusercontent.com/775692/28824041-020638a0-76c9-11e7-9db6-464654a4605e.png)
![image](https://user-images.githubusercontent.com/775692/28824054-0f28239a-76c9-11e7-84ab-3c6ecf8bb1b6.png)
![image](https://user-images.githubusercontent.com/775692/28824059-197d0978-76c9-11e7-9921-ce227916e9b0.png)

2017-08-01 11:53 UTC, imevro requested changes
фикси дизайн
кодстайл цсс суперхуевый

2017-08-02 10:31 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28869860-d807c21c-7786-11e7-995f-c480263e16a2.png)
![image](https://user-images.githubusercontent.com/775692/28869871-e3a719e2-7786-11e7-91d6-92f1dfc5055a.png)

2017-08-02 10:31 UTC, imevro requested changes
красава

2017-08-02 19:22 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28890804-038241b6-77d1-11e7-9c05-2b5cd2d3c336.png)
![image](https://user-images.githubusercontent.com/775692/28890833-161bf1c8-77d1-11e7-8b54-a58a3c7148ac.png)

2017-08-02 19:25 UTC, imevro requested changes

2017-08-02 19:25 UTC, evgenyrodionov commented on index.html
> +    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
почему идёт мета тайтл линк линк линк мета?

2017-08-02 19:25 UTC, evgenyrodionov commented on index.html
> +        <div class="wp-price-number">
product__info > wp-price-number? wtf?

2017-08-02 19:25 UTC, evgenyrodionov commented on index.html
> +        <p class="product__color-msg">Colour: Honey</p>
это цвет, это не мсдж

2017-08-02 19:25 UTC, evgenyrodionov commented on index.html
> +          Coat length: 98cm/38.6in. This is based on a size UK 48 as proportions change slightly according to size.<br>
это список

2017-08-02 19:25 UTC, evgenyrodionov commented on index.html
> +          Raglan sleeves and a concealed button closure complement the clean tailored lines.<br>
это параграфы

2017-08-02 19:25 UTC, evgenyrodionov commented on index.html
> +      <div class="recommend-list">
we-recommend > recommend-list?

2017-08-03 16:21 UTC, dartist21 commented
Сейчас с пиксель-хантингом должно быть всё ок. У меня уже остальные сайты  в глазах двоятся.

2017-08-04 07:27 UTC, imevro requested changes
- нейминг
- a11y

2017-08-04 14:04 UTC, imevro requested changes
в целом красава

2017-08-04 14:04 UTC, evgenyrodionov commented on css/index.css
> +  height: 400px;
ставь либо высоту фикс либо ширину

2017-08-04 14:04 UTC, evgenyrodionov commented on css/index.css
> +  height: 400px;
иначе пизда если пикча придёт с другими пропорциями

2017-08-04 19:19 UTC, imevro requested changes

2017-08-04 19:19 UTC, evgenyrodionov commented on css/index.css
> +  top: 25%;
не очень надежно, лучше top 0, bottom 0 и vertical-align middle

2017-08-05 09:55 UTC, imevro approved these changes

2017-08-06 20:20 UTC, merged

2017-08-06 20:20 UTC, evgenyrodionov commented
Гит чекаут мастер, гит пулл ориджин мастер --ребейз, новые бранчи от обновленного мастера