Feat/product page adaptive
dartist21/fake-burrberry-frontend pull request #2
Opened 2017-08-05 08:02 UTC by dartist21

2017-08-05 15:10 UTC, evgenyrodionov commented
Пикче одиноко без текста
Внизу ребят попидорасило
Контейнера нет

![image](https://user-images.githubusercontent.com/775692/28996432-534ddc02-7a09-11e7-8eed-611054dd5f01.png)

2017-08-05 15:11 UTC, imevro requested changes

2017-08-05 15:11 UTC, evgenyrodionov commented on css/index.css
> +  .read-more-accordion > ul {
`>` плохой селектор

2017-08-05 18:22 UTC, evgenyrodionov commented
Я не понял почему ты не растянешь пикчу на 100% колонки, а вместо этого дрочишь размеры колонок?

![image](https://user-images.githubusercontent.com/775692/28997725-14d81cce-7a24-11e7-97c7-182ce071d499.png)

2017-08-05 18:25 UTC, imevro requested changes

2017-08-05 18:25 UTC, evgenyrodionov commented on css/index.css
>  .delivery__par {
PAR? WHAT IS PAR?

2017-08-05 18:25 UTC, evgenyrodionov commented on css/index.css
> +    margin-left: -1px;
что это за костыль

2017-08-05 18:25 UTC, evgenyrodionov commented on css/index.css
> +    height: 576px;
нельзя суперфиксить

2017-08-05 18:25 UTC, evgenyrodionov commented on css/index.css
> +    width: 100%;
что будет если с сервера придёт пикча с нестаднартным aspect ratio

2017-08-05 18:25 UTC, evgenyrodionov commented on index.html
> +        <button type="button" name="shipping-country" class="footer__button">Shipping country: Russian Federation</button><button type="button" name="language" class="footer__button">Language: Englis
не понял зачем ты убрал перенос строки

2017-08-05 18:54 UTC, dartist21 commented on css/index.css
> +    height: 576px;
но ведь можно оставить одну размерность? например, высоту
<img width="207" alt="screen shot 2017-08-05 at 21 53 57" src="https://user-images.githubusercontent.com/14904053/28997907-9ef47728-7a28-11e7-8fd4-07d23daf2c9e.png">

2017-08-06 20:21 UTC, imevro approved these changes

2017-08-06 20:22 UTC, merged