feat/product-page-react
dartist21/fake-burrberry-frontend pull request #5
Opened 2017-08-08 10:09 UTC by dartist21

2017-08-08 16:42 UTC, dartist21 commented
1. перенести страницы как есть и попробовать чтобы они заработали – done
2. разбивать страницы на крупные компоненты-этажи – done

Завтра продолжу разбивать на компоненты и и цсс уберу  в стайлед-компонентс.

2017-08-09 09:34 UTC, imevro requested changes
в телеграфе расписал

- Тайтлы через react-helmet
- Нормальные manifest.json и package.json
- README.md должен быть про проект
- Нейминг должен быть корректным
- Архитектура должна быть про продукт
- Функции — тупым компонентам, классы — рабочим

2017-08-10 17:51 UTC, imevro requested changes

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Footer/Navigation.jsx
> +              Contact Us
ебать, зачем одну строку разносить на три!

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/Button.jsx
> +    <Button backgroundColor={props.backgroundColor} textColor={props.textColor}
плохие имена пропов, не нравятся

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/Button.jsx
> +    <Button backgroundColor={props.backgroundColor} textColor={props.textColor}
value/label лучше будут

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/ColorBtn.jsx
> +              active = {props.active}
поставь преттир

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/Product.jsx
> +            <Button backgroundColor="#171717" textColor="#ffffff" text="SELECT A SIZE"></Button>
почему текст не передавать между тегов как на 69 строчке?

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/Recomendations.jsx
> +            image = "img/img4.jpg"
воробей пролетит между пропом и значением

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/index.js
> +  let descriptionParagraph =
без мутабельности плз

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/index.js
> +  let descriptionParagraph =
и описание должно быть строкой

2017-08-10 17:51 UTC, evgenyrodionov commented on src/Product/index.js
> +                         className="read-more-accordion" />
откуда класснейм если у нас ск

2017-08-11 11:09 UTC, imevro approved these changes

2017-08-11 11:10 UTC, evgenyrodionov commented
Вроде всё ок, делай десктоп в отдельной ветке от этой

2017-08-13 00:16 UTC, dartist21 commented
Это старый подтвержденный пр с реактом для таблета и телефона, новый полный пр тут: 

https://github.com/dartist21/fake-burrberry-frontend/pull/6

2017-08-13 10:56 UTC, closed without merging