Feat/product page react desctop
dartist21/fake-burrberry-frontend pull request #6
Opened 2017-08-12 08:57 UTC by dartist21

2017-08-12 09:00 UTC, dartist21 commented
Сделал десктоп футер, хедер, рекомендации, деливери.

Не сделал десктоп главной панельки и не до конца десктоп описания.

2017-08-12 12:15 UTC, imevro requested changes

2017-08-12 12:15 UTC, evgenyrodionov commented on src/Product/BreakPoints.jsx
> +  <Responsive minWidth={'62rem'} children={children} />;
чилдрен нужно между тегов передавать

2017-08-12 12:15 UTC, evgenyrodionov commented on src/Product/BreakPoints.jsx
> +  <Responsive maxWidth={767} children={children} />;
поч тут пиксели, а выше ремы

2017-08-12 12:15 UTC, evgenyrodionov commented on src/Product/Recomendations.jsx
> +import RecomendationCard from './RecomendationCard';
сделай директорию Recommendations, если у тебя в Product уже два файла лежат, которые относятся к этому разделу

2017-08-12 16:52 UTC, dartist21 commented
Там хотел переименовать ветку, но потом не смог с нее сделать пуш в этот пр. Поэтому вернул обратно ветку и новый пр удалил.

2017-08-12 19:24 UTC, imevro requested changes

2017-08-12 19:24 UTC, evgenyrodionov commented on src/Product/BreakPoints.jsx
> +export const MaxDeviceWidthLarge = ({ children }) =>
какой сложный нейминг

2017-08-12 19:24 UTC, evgenyrodionov commented on src/Product/MainInfo.jsx
> +            <ColorBtn colorValue="#cfa880" colorName="fawn" active="active" />
active="active"? храни булеаном

2017-08-12 19:24 UTC, evgenyrodionov commented on src/Product/Product.jsx
> +            <Title>Long Cotton Gabardine Car Coat Coat Coat Coat Coat</Title>
почему у тебя два тайтла отличаются?

2017-08-12 19:24 UTC, evgenyrodionov commented on src/Product/Recomendations/index.jsx
> +import RecomendationCard from './RecomendationCard';
зачем столько префиксов если ты уже в директории рекомендейшн

2017-08-12 19:24 UTC, evgenyrodionov commented on src/Product/index.js
> +    margin-left: -50vw;
зачем этот костыль???

2017-08-12 19:24 UTC, evgenyrodionov commented on src/Product/index.js
> +    margin-left: -50vw;
вытащи блок с бэкграундом за пределы контейнера и всё

2017-08-13 10:56 UTC, imevro approved these changes

2017-08-13 10:56 UTC, merged