feat: add eslint, husky, travis
dartist21/fake-burrberry-frontend pull request #8
Opened 2017-08-18 13:59 UTC by dartist21

2017-08-18 15:43 UTC, imevro requested changes

2017-08-18 15:43 UTC, evgenyrodionov commented on src/Product/Button.jsx
> +export default function Export(props) {
плохое название компонента

2017-08-18 15:43 UTC, evgenyrodionov commented on src/registerServiceWorker.js
> +/* eslint-disable */
укажи конкретные правила

2017-08-18 19:41 UTC, dartist21 commented
только не удаляй ветку, я от нее сделаю ветку под лист

2017-08-18 22:13 UTC, imevro approved these changes

2017-08-20 06:17 UTC, dartist21 commented
Актуальный пулл реквест https://github.com/dartist21/fake-burrberry-frontend/pull/9

Этот подвешиваю так как последняя проверка

2017-08-20 09:34 UTC, evgenyrodionov commented
Красава!

2017-08-20 09:43 UTC, closed without merging