feat: product page list
dartist21/fake-burrberry-frontend pull request #9
Opened 2017-08-19 02:54 UTC by dartist21

2017-08-19 08:07 UTC, dartist21 commented
<img width="487" alt="screen shot 2017-08-19 at 11 01 14" src="https://user-images.githubusercontent.com/14904053/29484768-569aca62-84ce-11e7-9e4b-50884e684268.png">
В макете текст карточки заезжает под лайк, ты сказал делать так, чтобы не заезжал.

<img width="711" alt="screen shot 2017-08-19 at 10 43 30" src="https://user-images.githubusercontent.com/14904053/29484776-7239ae96-84ce-11e7-8dee-d27cc61cc517.png">
Тут расхождение из-за проблем с макетом
<img width="298" alt="screen shot 2017-08-19 at 11 06 56" src="https://user-images.githubusercontent.com/14904053/29484782-8a5ff534-84ce-11e7-9cc8-3bce73a11f57.png">
<img width="289" alt="screen shot 2017-08-19 at 11 06 50" src="https://user-images.githubusercontent.com/14904053/29484783-8a6323b2-84ce-11e7-8841-30abcdc728ee.png">

2017-08-19 08:22 UTC, dartist21 commented
Деплой https://build-bggkvjyvca.now.sh/

Пока готова только мобильная версия

<img width="530" alt="screen shot 2017-08-19 at 11 22 22" src="https://user-images.githubusercontent.com/14904053/29484877-b9b167bc-84d0-11e7-85a2-5f2c5f254280.png">

2017-08-19 10:02 UTC, evgenyrodionov commented
Дыра
![image](https://user-images.githubusercontent.com/775692/29485688-aee9cb54-84de-11e7-98f2-2bfe6c14fa8a.png)

2017-08-19 10:05 UTC, imevro requested changes

2017-08-19 10:05 UTC, evgenyrodionov commented on src/App.jsx
> +            <title>Long Cotton Gabardine Car Coat | Men - Burberry</title>
что это делает на главной странице? это же заголовок про товар

2017-08-19 10:05 UTC, evgenyrodionov commented on src/App.jsx
> +          <Route exact path="/products/mens-clothing" component={List} />
зачем префикс продактс?

2017-08-19 10:05 UTC, evgenyrodionov commented on src/Product/Product.jsx
> +          <Image src="/img/img1.jpg" alt="Long Cotton Gabardine Car Coat" />
где тут паблик урл

2017-08-19 10:05 UTC, evgenyrodionov commented on src/Product/index.jsx
> +                src={`${process.env.PUBLIC_URL}/img/img9.jpg`}
почему бы не взять сразу с серверов берберри?

2017-08-19 14:33 UTC, dartist21 commented on src/Product/index.jsx
> +                src={`${process.env.PUBLIC_URL}/img/img9.jpg`}
Это картинка к нашему уникальному пальто, картинки карточек поменял.

2017-08-19 16:57 UTC, dartist21 commented
https://build-xkjmshzyap.now.sh

На деплое пропало 2 картинки и не хочет обновлять деплой. Наверное, деплоить можно раз в какое-то время.

2017-08-19 20:50 UTC, evgenyrodionov commented
Слишком жирный шрифт

![image](https://user-images.githubusercontent.com/775692/29490053-1b0bda16-8539-11e7-9ae1-6fcd91e6f54b.png)

2017-08-19 20:50 UTC, evgenyrodionov commented
Тут тоже

![image](https://user-images.githubusercontent.com/775692/29490054-2f498b68-8539-11e7-83d4-c83240c59594.png)

2017-08-19 20:58 UTC, imevro requested changes

2017-08-19 20:58 UTC, evgenyrodionov commented on src/App.jsx
> +import List from './Product/List';
продакт/лист? это как?

2017-08-19 20:58 UTC, evgenyrodionov commented on src/App.jsx
> +addLocaleData([...ru]);
можно просто (ru), зачем создавать ещё один массив

2017-08-19 20:58 UTC, evgenyrodionov commented on src/Footer/Navigation.jsx
> +import { Large } from '../Product/Show/BreakPoints';
тебя не смущает что для футера тебе нужно лезть в `Product/Show` ради генерик-компонента `Large`?

2017-08-19 20:58 UTC, evgenyrodionov commented on src/Footer/Navigation.jsx
> +const ImageTitle = styled.a`
у тебя же реакт-роутер

2017-08-20 06:13 UTC, dartist21 commented
https://build-tfhlvzdkty.now.sh/

2017-08-20 09:43 UTC, imevro approved these changes

2017-08-20 09:43 UTC, merged